--*** USER: SYSTEM ***
CREATE USER C##GUIA_N2 IDENTIFIED BY 1234 DEFAULT TABLESPACE SYSAUX QUOTA 5M ON SYSAUX;
GRANT CONNECT, RESOURCE TO C##GUIA_N2;

--*** USER: C##GUIA_N2 ***
--Ejercicio 1
SELECT
    SUBSTR(RUTEMP, 0, LENGTH(RUTEMP)-1) || '-' || SUBSTR(RUTEMP, -1) RUN_EMPLEADO,
    PATERNO || ' ' || MATERNO || ' ' || NOMBRE NOMBRE,
    DIRECCION,
    FONO1,
    NVL(FONO2, 'NO POSEE FONO')
FROM EMPLEADO
ORDER BY 2;

--Ejercicio 2
SELECT
    SUBSTR(RUTEMP, 0, LENGTH(RUTEMP)-1) || '-' || SUBSTR(RUTEMP, LENGTH(RUTEMP)) RUN_EMPLEADO,
    --PATERNO || ' ' || MATERNO || ' ' || NOMBRE NOMBRE
    TO_CHAR(SUELDO, '$9g999g999') AS SUELDO,
    LPAD(TRUNC(SUELDO/100000) || '%', 11, ' ') AS PORCENTAJE
FROM EMPLEADO
WHERE IDCATEGORIA=2
ORDER BY 1;

--Ejercicio 3
SELECT
    INITCAP(PATERNO ||' '|| MATERNO ||' '|| NOMBRE) EMPLEADO,
    LOWER(SUBSTR(NOMBRE, 1, 2) ||'.'|| PATERNO) NOM_USUARIO,
    LOWER(SUBSTR(ECIVIL, 1, 1) ||'*'|| SUBSTR(RUTEMP, 1, 4) || SUBSTR(DIRECCION, 1, 1)) ||'_'|| UPPER(SUBSTR(DIRECCION, 2, 1)) CONTRASEÑA
FROM EMPLEADO
ORDER BY NOMBRE;

--Ejercicio 4
SELECT
    SUBSTR(RUTEMP, 1, LENGTH(RUTEMP)-1) ||'-'|| SUBSTR(RUTEMP, -1) RUN_EMPLEADO,
    UPPER(PATERNO ||' '|| MATERNO ||' '|| NOMBRE) NOMBRE,
    SUELDO SUELDO,
    ROUND(SUELDO*
    CASE
        WHEN PUNTAJE>500 THEN 1.35
        WHEN PUNTAJE<=500 AND PUNTAJE>=301 THEN 1.25
        WHEN PUNTAJE<=300 AND PUNTAJE>=15 THEN 1.15
        ELSE 1
    END) "SUELDO AUMENTADO"
FROM EMPLEADO
ORDER BY PATERNO;

--Ejercicio 5
SELECT
    NUMPROPIEDAD,
    IDTIPO TIPO,
    RENTA,
    NVL(GASTOCOMUN, 0) AS "GASTOS COMUNES",
    RENTA*1.062 AS "NUEVA RENTA",
    NVL(GASTOCOMUN, 0)*1.062 AS "GASTO COMUN REAJUSTADO"
FROM PROPIEDAD
WHERE UPPER(IDTIPO) IN ('A', 'B'); -- ='A' OR UPPER(IDTIPO)='B'; -- UPPER('&INGRESE_LETRA');

--Ejercicio 6
SELECT
    LPAD(SUBSTR(RUTCLI, 0, LENGTH(RUTCLI)-1) || '-' || SUBSTR(RUTCLI, -1), 10, 0) RUT,
    INITCAP(NOMCLI) AS "NOMBRE CLIENTE",
    DIRECCION,
    FONO1 AS "FONO CLIENTE",
    NVL(FONO2, 'NO REGISTRA') AS "FONO CONTACTO"
FROM CLIENTE
WHERE UPPER(ECIVIL)='SOLTERO' AND UPPER(IDTIPO)='B'
ORDER BY NOMCLI DESC;