-- MDY 1131 - 009D - Prueba 3
-- Álvaro Agustín Arenas Cornejo

-- User: SYSTEM

-- Crear un usuario nuevo para el owner
CREATE USER C##TALLER_MECANICO IDENTIFIED BY 1234 DEFAULT TABLESPACE SYSAUX QUOTA 10M ON SYSAUX;

-- Otorgar privilegios para CONECTAR y RECURSOS
GRANT CONNECT, RESOURCE TO C##TALLER_MECANICO;


-- User: C##TALLER_MECANICO

-- Crear tabla COMUNA
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

CREATE TABLE COMUNA (
IDCOMUNA NUMBER(3) CONSTRAINT COMUNA_PK PRIMARY KEY,
NOMBRECOMUNA VARCHAR2(25) NOT NULL
);

-- Crear tabla MARCA
CREATE TABLE MARCA (
ID NUMBER(3) CONSTRAINT MARCA_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(25) NOT NULL
);

-- Crear tabla TIPO_PROD
CREATE TABLE TIPO_PROD (
COD NUMBER(3) CONSTRAINT TIPO_PRODUCTO_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(30) NOT NULL
);

-- Crear tabla FAMILIA_PROD
CREATE TABLE FAMILIA_PROD (
IDFAMILIA NUMBER(3) CONSTRAINT FAMILIA_PRODUCTO_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(30) NOT NULL
);

-- Crear tabla PROVEEDOR
CREATE TABLE PROVEEDOR (
ID_PROVEEDOR NUMBER(3) CONSTRAINT PROVEEDOR_PK PRIMARY KEY,
RUBRO VARCHAR2(25) NOT NULL,
RAZON_SOCIAL VARCHAR2(25) NOT NULL,
NTELEFONO VARCHAR2(12) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL,
DIRECCION_PROV VARCHAR2(50) NOT NULL,
FECHA_CONTRATO DATE NOT NULL
);

-- Crear tabla FACTURA
CREATE TABLE FACTURA (
ID_FACTURA NUMBER(3) CONSTRAINT FACTURA_PK PRIMARY KEY,
FECHA DATE NOT NULL,
TOTAL NUMBER(8) NOT NULL
);

-- Crear tabla EMPLEADO
CREATE TABLE EMPLEADO (
IDEMPLEADO NUMBER(3) CONSTRAINT EMPLEADO_PK PRIMARY KEY,
RUT NUMBER(8) CONSTRAINT EMPLEADO_RUT_UK UNIQUE,
DV CHAR(1) NOT NULL,
P_NOMBER VARCHAR2(25) NOT NULL,
APELLIDOS VARCHAR2(25) NOT NULL,
DIRECCION VARCHAR2(30) NOT NULL,
TIPOEMPLEADO VARCHAR2(25) NOT NULL
);

-- Crear tabla CLIENTE
CREATE TABLE CLIENTE (
IDCLIENTE NUMBER(3) CONSTRAINT CLIENTE_PK PRIMARY KEY,
RUT NUMBER(8) NOT NULL CONSTRAINT CLIENTE_RUT_UN UNIQUE,
DV CHAR(1) NOT NULL CONSTRAINT CLIENTE_DV_CK CHECK (DV IN ('1','2','3','4','5','6','7','8','9','0','K')),
PRIMERNOMBRE VARCHAR2(25) NOT NULL,
SEGUNDONOMBRE VARCHAR2(25),
APELLIDO_P VARCHAR2(25) NOT NULL,
APELLIDOS_M VARCHAR2(25) NOT NULL,
DIRECCION VARCHAR2(30) NOT NULL,
USUARIO VARCHAR2(25) NOT NULL,
CLAVE VARCHAR2(25) NOT NULL CONSTRAINT CLIENTE_CLAVE_CK CHECK (CLAVE>199),
PUNTAJE INTEGER,
COMUNA_IDCOMUNA NUMBER(3) NOT NULL CONSTRAINT CLIENTE_COMUNA_FK REFERENCES COMUNA (IDCOMUNA)
);

-- Crear tabla VEHÍCULO
CREATE TABLE VEHICULO (
PATENTE CHAR(6) CONSTRAINT AUTO_PK PRIMARY KEY,
COLOR VARCHAR2(25) NOT NULL,
ANNIO_FABRICA NUMBER(4) NOT NULL CONSTRAINT VEHICULO_ANNIO_FABRICA_CK CHECK (ANNIO_FABRICA<2006),
CHASIS VARCHAR2(15) NOT NULL,
KILOMETRAJE NUMBER(7) NOT NULL CONSTRAINT VEHICULO_KILOMMETRAJE_CK CHECK (KILOMETRAJE<70001),
MARCA_ID NUMBER(3) NOT NULL CONSTRAINT VEHICULO_MARCA_FK REFERENCES MARCA (ID),
IDCLIENTE NUMBER(3) NOT NULL CONSTRAINT VEHICULO_CLIENTE_FK REFERENCES CLIENTE (IDCLIENTE)
);

-- Crear tabla ORDEN_DE_COMPRA
CREATE TABLE ORDEN_DE_COMPRA (
IDORDENDECOMPRA NUMBER(3) CONSTRAINT ORDEN_DE_COMPRA_PK PRIMARY KEY,
ESTADO VARCHAR2(2) NOT NULL,
CLIENTE_ID NUMBER(3) NOT NULL CONSTRAINT ORDEN_DE_COMPRA_CLIENTE_FK REFERENCES CLIENTE (IDCLIENTE),
IDEMPLEADO NUMBER(3) NOT NULL CONSTRAINT ORDEN_DE_COMPRA_EMPLEADO_FK REFERENCES EMPLEADO (IDEMPLEADO)
);

-- Crear tabla PRODUCTO
-- Nota al margen: Constraint CHECK de StockCritico cambiada para ser coherente con NUMBER(2)
CREATE TABLE PRODUCTO (
IDPRODUCTO NUMBER(17) CONSTRAINT PRODUCTO_PK PRIMARY KEY,
DESCRIPCION VARCHAR2(30) NOT NULL,
PRECIOCOMPRA NUMBER(8) NOT NULL,
PRECIOVENTA NUMBER(8) NOT NULL,
STOCK NUMBER(4) NOT NULL,
STOCKCRITICO NUMBER(2) NOT NULL CONSTRAINT PRODUCTO_STOCKCRITICO_CK CHECK (STOCKCRITICO<25), 
FECHAVENCIMIENTO DATE NOT NULL,
TIPO NUMBER(3) NOT NULL,
ID_PROVEE NUMBER(3) NOT NULL CONSTRAINT PRODUCTO_PROVE_FK REFERENCES PROVEEDOR (ID_PROVEEDOR),
ID_FAMILIA NUMBER(3) NOT NULL CONSTRAINT FAMILIA_PRODUCTO_FK REFERENCES FAMILIA_PROD (IDFAMILIA),
CODTIPO NUMBER(3) NOT NULL CONSTRAINT PRO_TIPO_PROD_FK REFERENCES TIPO_PROD (COD),
ID_ODC NUMBER(3) NOT NULL CONSTRAINT PRODUCTO_ORDEN_DE_COMPRA_FK REFERENCES ORDEN_DE_COMPRA (IDORDENDECOMPRA)
);

-- Crear tabla DETALLE_FACT
CREATE TABLE DETALLE_FACT (
ID_DETALLE NUMBER(6) NOT NULL,
FACTURA_ID NUMBER(3) NOT NULL CONSTRAINT DETALLE_FACTURA_FACTURA_FK REFERENCES FACTURA (ID_FACTURA),
ID_PROD NUMBER(17) NOT NULL CONSTRAINT DETALLE_FACTURA_PRODUCTO_FK REFERENCES PRODUCTO (IDPRODUCTO),
CANTIDAD NUMBER(3) NOT NULL,
CONSTRAINT DETALLE_FACTURA_PK PRIMARY KEY (ID_DETALLE, FACTURA_ID, ID_PROD)
);


-- CREAR SECUENCIAS PARA LAS IDs

-- CREAR SEQUENCIA PARA EL ID DE PRODUCTO
CREATE SEQUENCE SEQ_ID_PRODUCTO
	START WITH 10000
	INCREMENT BY 5;

-- CREAR SEQUENCIA PARA EL ID DE MARCA
CREATE SEQUENCE SEQ_ID_MARCA
	START WITH 10;

-- CREAR SEQUENCIA PARA EL ID DE COMUNA
CREATE SEQUENCE SEQ_ID_COMUNA;

-- CREAR SEQUENCIA PARA EL ID DE EMPLEADO
CREATE SEQUENCE SEQ_ID_EMPLEADO;

-- CREAR SEQUENCIA PARA EL ID DE TIPO_PRODUCTO
CREATE SEQUENCE SEQ_ID_TIPO_PRODUCTO;

-- CREAR SEQUENCIA PARA EL ID DE PROVEEDOR
CREATE SEQUENCE SEQ_ID_PROVEEDOR;

-- CREAR SEQUENCIA PARA EL ID DE FAMILIA_PROD
CREATE SEQUENCE SEQ_ID_FAMILIA_PROD;

-- CREAR SEQUENCIA PARA EL ID DE CLIENTE
CREATE SEQUENCE SEQ_ID_CLIENTE;

-- CREAR SEQUENCIA PARA EL ID DE ORDEN_DE_COMPRA
CREATE SEQUENCE SEQ_ID_ODC;


-- POBLAR DATOS

-- POBLAR COMUNASINSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Alhué');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Buin');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Calera de Tango');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Cerrillos');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Cerro Navia');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Colina');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Conchalí');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Curacaví');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Santiago');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Providencia');
INSERT INTO comuna VALUES (SEQ_ID_COMUNA.nextval, 'Maipú');

-- POBLAR EMPLEADOS
INSERT INTO empleado VALUES 
(SEQ_ID_EMPLEADO.nextval, 18611254, 'K', 'Christian', 'Duarte Muñoz', 'Maipú', 'Mecánico');

INSERT INTO empleado VALUES 
(SEQ_ID_EMPLEADO.nextval, 17548951, '3', 'Isaias', 'Inostroza Rojas', 'Maipú', 'Mecánico');

INSERT INTO empleado VALUES 
(SEQ_ID_EMPLEADO.nextval, 20845235, '1', 'Juan', 'Pérez Díaz', 'Maipú', 'Mecánico');

INSERT INTO empleado VALUES 
(SEQ_ID_EMPLEADO.nextval, 22514846, '8', 'Alonso', 'Soto Contreras', 'Maipú', 'Mecánico');

-- POBLAR MARCA
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Ford');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Mazda');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Peugeot');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Toyota');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Hyundai');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Nissan');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Kia');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Suzuki');
INSERT INTO marca VALUES (SEQ_ID_MARCA.nextval, 'Chevrolet');

-- POBLAR TIPO_PROD
INSERT INTO tipo_prod VALUES (SEQ_ID_TIPO_PRODUCTO.nextval, 'Chasis');
INSERT INTO tipo_prod VALUES (SEQ_ID_TIPO_PRODUCTO.nextval, 'Aceite');
INSERT INTO tipo_prod VALUES (SEQ_ID_TIPO_PRODUCTO.nextval, 'Agua destilada');
INSERT INTO tipo_prod VALUES (SEQ_ID_TIPO_PRODUCTO.nextval, 'Parabrisas');
INSERT INTO tipo_prod VALUES (SEQ_ID_TIPO_PRODUCTO.nextval, 'Vidrios');
INSERT INTO tipo_prod VALUES (SEQ_ID_TIPO_PRODUCTO.nextval, 'Frenos');

-- POBLAR PROVEEDOR
-- Nota al magen: Intenté rellenar DATE con '18/jan/2018', pero no me lo aceptó. Con '18/01/2018', me lo aceptó bien.
INSERT INTO proveedor VALUES 
(SEQ_ID_PROVEEDOR.nextval, 'Taller de precisión', 'Bosch S.A.', 22245786, 
'contacto@bosch.cl', 'Las condes', '18/01/2018');

INSERT INTO proveedor VALUES 
(SEQ_ID_PROVEEDOR.nextval, 'Piezas pequeñas', 'Murillo y hmnos', 22251346, 
'clientes@murillohmnos.cl', 'Recoleta', '21/03/2018');

-- POBLAR FAMILIA_PROD
INSERT INTO familia_prod VALUES (SEQ_ID_FAMILIA_PROD.nextval, 'Pastillas de frenos');
INSERT INTO familia_prod VALUES (SEQ_ID_FAMILIA_PROD.nextval, 'Vidrio lateral');
INSERT INTO familia_prod VALUES (SEQ_ID_FAMILIA_PROD.nextval, 'Aceite de motor');

-- POBLAR CLIENTE
INSERT INTO cliente VALUES 
(SEQ_ID_CLIENTE.nextval, 15423512, 'K', 'Gabriel', 'Samuel', 'Inostroza', 'Lorca', 
'El rosal 2523', 'Gab.Ino', '1234', 500, 10);

INSERT INTO cliente VALUES 
(SEQ_ID_CLIENTE.nextval, 17534123, '3', 'Sofía', 'Agustina', 'Labra', 'Duarte', 
'El rosal 2134', 'Sof.Lab', '4321', 750, 10);

INSERT INTO cliente VALUES 
(SEQ_ID_CLIENTE.nextval, 20145785, '1', 'Isidora', 'Emilia', 'Silva', 'Contreras', 
'El rosal 1523', 'Isi.Sil', '21022000', 921, 10);

-- POBLAR ORDEN DE COMPRA

INSERT INTO orden_de_compra VALUES (SEQ_ID_ODC.nextval, 'P', 1, 1);
INSERT INTO orden_de_compra VALUES (SEQ_ID_ODC.nextval, 'A', 2, 2);
INSERT INTO orden_de_compra VALUES (SEQ_ID_ODC.nextval, 'A', 2, 1);

-- POBLAR PRODUCTO
INSERT INTO producto VALUES
(SEQ_ID_PRODUCTO.nextval, 'Pastillas de Freno DFS', 18000, 30000, 500, 20, '21/08/2021', 001,
1, 1, 6, 1);

INSERT INTO producto VALUES
(SEQ_ID_PRODUCTO.nextval, 'Pastillas de Freno DFS', 18000, 30000, 500, 20, '21/08/2021', 001,
1, 1, 6, 2);

INSERT INTO producto VALUES
(SEQ_ID_PRODUCTO.nextval, 'Aceite 5W-30', 25000, 48900, 64, 15, '14/03/2023', 002,
1, 3, 2, 3);

INSERT INTO producto VALUES
(SEQ_ID_PRODUCTO.nextval, 'Vidrio lateral trasero', 18000, 30000, 29, 5, '01/01/2025', 003,
2, 2, 5, 3);

-- IMPORTANTE - SUBIR A DISCO
COMMIT;


-- DESNORMALIZAR PARA AUMENTAR RENDIMIENTO

-- DESNORMALIZAR MARCA
ALTER TABLE marca ADD vehiculo_x_marca NUMBER(5) DEFAULT 0;

-- DESNORMALIZAR COMUNA
ALTER TABLE comuna ADD residente_x_comuna NUMBER(5) DEFAULT 0;

-- UPDATE comuna SET residente_x_comuna=3 WHERE idcomuna=10;
-- COMMIT;