-- User: ADMIN

-- Crear un usuario nuevo para el owner
CREATE USER DUMBO IDENTIFIED BY ora1234_CLOUD DEFAULT TABLESPACE DATA QUOTA 1M ON DATA;

-- Otorgar privilegios para CONECTAR y RECURSOS
GRANT CONNECT, RESOURCE TO DUMBO;

-- User: DUMBO

-- Crear tabla SUCURSAL
CREATE TABLE SUCURSAL(
	id_codigo NUMBER(3)  NOT NULL CONSTRAINT PK_SUCURSAL PRIMARY KEY,
	nombre    VARCHAR2(25) NOT NULL,
	direccion VARCHAR2(30) NOT NULL,
	telefono  NUMBER(10)   NOT NULL
);