-- USER: SYSTEM

CREATE USER C##HOLA IDENTIFIED BY 1234 DEFAULT TABLESPACE SYSAUX QUOTA 8M ON SYSAUX;

GRANT CONNECT, RESOURCE TO C##HOLA

--USER C##HOLA

CREATE TABLE saludo
(	id_saludo	NUMBER(2)		NOT NULL	CONSTRAINT pk_saludo PRIMARY KEY,
	descripcion VARCHAR2(25)	NOT NULL	CONSTRAINT uk_saludo UNIQUE,
	id_persona	NUMBER(3)		NOT NULL 	CONSTRAINT FOREIGN KEY REFERENCES PERSONA (id_persona)
);